source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'FormKit_Example', :exclusive => true do
  pod "FormKit", :path => "../"
end

target 'FormKit_Tests', :exclusive => true do
  pod "FormKit", :path => "../"
end
